@echo off
rem -----------------------------------------------------------------------------
rem This file was generated by the Gradle Wrapper. Do not edit it directly.
rem
rem Gradle version: <YOUR_GRADLE_VERSION_HERE>
rem
rem See Gradle documentation for details: https://docs.gradle.org/<YOUR_GRADLE_VERSION_HERE>/userguide/gradle_wrapper.html
rem -----------------------------------------------------------------------------

set GRADLE_HOME=%~dp0gradle-%YOUR_GRADLE_VERSION_HERE%-bin
if not exist "%GRADLE_HOME%\bin\gradle" (
    echo Downloading Gradle...
    curl -sL https://services.gradle.org/distributions/gradle-%YOUR_GRADLE_VERSION_HERE%-bin.zip -o gradle.zip
    powershell -Command "Expand-Archive gradle.zip -DestinationPath %GRADLE_HOME%"
    del gradle.zip
)

"%GRADLE_HOME%\bin\gradle" %*
