name: Mobile App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Android APK
        run: ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/apk/release/app-release.apk

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          cd ios
          pod install
      - name: Build iOS IPA
        run: |
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -archivePath ios/build/YourApp.xcarchive archive
          xcodebuild -exportArchive -archivePath ios/build/YourApp.xcarchive -exportPath ios/build/YourApp.ipa -exportOptionsPlist ios/ExportOptions.plist
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/YourApp.ipa
